[package]
name = "sounds_good"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
hound = "3.5.0"
portaudio = "0.7.0"
rodio = "0.17.1"

[build-dependencies]
portaudio = "0.7.0"
